{% set name = "devcontainer-cli" %}
{% set version = "0.71.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/devcontainers/cli/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 34fade4c75d4081dd1c6edfeb2cea15c18ca551263162599689f06009f53b532

build:
  number: 0
  noarch: generic
  script:
    - yarn install

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - make
    - yarn
  host:
    - nodejs >=20
  run:
    - nodejs >=20
    - {{ compiler('cxx') }}

test:
  commands:
    - test -f $PREFIX/bin/devcontainer
    - devcontainer --version

about:
  home: https://github.com/devcontainers/cli
  summary: 'A reference implementation for the specification that can create and configure a dev container from a devcontainer.json. '
  description: |
    A development container allows you to use a container as a full-featured development environment. It can be used to run an application, to separate tools, libraries, or runtimes needed for working with a codebase, and to aid in continuous integration and testing. Dev containers can be run locally or remotely, in a private or public cloud.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - freundTech
